name: Build MangoModLoader
on: push

permissions:
  contents: write

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@v0
    with:
      java: 21
      gradle_tasks: :publishAllPublicationsToMavenRepository
      artifact_name: "mangomodloader"
      artifact_group: "org.mangorage"
      author_icon_url: "https://avatars.githubusercontent.com/u/147930550"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MAVEN_USER: "mango"
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}  # Reference the secret